title: "Gries, this is me"
description: "All about gries aka Christoph Rosse"
logo: "logo.png"

# Your site's domain. E.g: http://yoursite.com
url: ""

# Comments in posts
comments:
    enabled: false
    disqus_shortname:

# Information about author
author:
    name: gries

    # Social networks
    twitter: griesx
    github: https://github.com/gries

# RSS feed
feed:
    max_item: 10

# Code highlight for <pre> and <code> tags
# Powered by http://highlightjs.org/
code_highlight: true

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: / }
    - { name: CV, url: /cv }

bottom_menu:
    - { name: my github, url: https://github.com/gries }

paginate: 5

exclude: ['README.md', 'LICENSE','composer.json']
